services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ttt
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure


  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      app:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ttt
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ttt"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
